# Generated by Django 5.1.3 on 2024-11-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_timer', '0002_timers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timers',
            old_name='minutes',
            new_name='focus',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='seconds',
        ),
        migrations.AddField(
            model_name='timers',
            name='rest',
            field=models.IntegerField(default=5),
        ),
    ]
