# Generated by Django 5.1.6 on 2025-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_timer', '0003_rename_minutes_timers_focus_remove_timers_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
