# Generated by Django 5.1.6 on 2025-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_timer', '0008_alter_customuser_selected_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='color1',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='themes',
            name='color2',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='themes',
            name='color3',
            field=models.CharField(max_length=7),
        ),
    ]
